name: Preview Build and Deploy to Netlify

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: '8.x'

    - name: Build
    - run: yarn
    - run: gulp:xslt
    - run: gulp:deploy

    - name: Deploy to Netlfiy
      uses: danakim/gh-action-deploy-netlify@v1
      with:
        node-version: '16.x'
