name: Preview Build and Deploy to Netlify

on:
  push:
    branches: [ develop ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'

    - name: Build
      run: yarn
 
    - name: Deploy to Netlfiy
    - uses: actions/setup-node@v2
      with:
        node-version: '8.x'
      
    - uses: danakim/gh-action-deploy-netlify@v1
      with:
        node-version: '16.x'
