name: Preview Build and Deploy to Netlify

on:
  push:
    branches: [ develop ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v1
      
      - name: Prepare Node 8
        uses: actions/setup-node@v1
        with:
          node-version: '8.x'
          
      - run: node -v
      # - run: npm rebuild --all
      # - run: npm install
      - run: ls ${{ github.workspace }}
 
      - name: Prepare Node 16
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
        
      - name: Deploy to Netlify
        uses: danakim/gh-action-deploy-netlify@v1
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: 'Deployed via GitHub Actions'
          build_directory: 'dist'
